import type { Trip, InboxMessage, Connection } from './types';

export const trips: Trip[] = [
  {
    id: 'scandinavia-2025',
    title: 'Summer in Scandinavia',
    startDate: '2025-07-20',
    endDate: '2025-07-27',
    image: {
      url: 'https://placehold.co/600x400.png',
      aiHint: 'scandinavia landscape',
    },
    itinerary: [
      {
        date: '2025-07-20',
        day: 'Saturday',
        segments: [
          {
            id: 'seg1',
            type: 'flight',
            status: 'confirmed',
            title: 'Flight to Copenhagen',
            provider: 'Scandinavian Airlines',
            confirmationCode: 'SK944',
            startTime: '14:30',
            endTime: '16:50',
            startLocation: 'Charles de Gaulle Airport',
            endLocation: 'Copenhagen Airport',
            startLocationShort: 'CDG',
            endLocationShort: 'CPH',
            duration: '2h 20m',
            details: { Gate: '42B', Seat: '18A', Terminal: '2D' },
          },
          {
            id: 'seg2',
            type: 'lodging',
            status: 'confirmed',
            title: 'Copenhagen Hotel',
            provider: 'Absalon Hotel',
            confirmationCode: 'BK12984',
            startTime: '18:00',
            endTime: '11:00 (July 23)',
            startLocation: 'Helgolandsgade 15, 1653 Copenhagen',
            endLocation: 'Helgolandsgade 15, 1653 Copenhagen',
            startLocationShort: 'Absalon Hotel',
            endLocationShort: 'Absalon Hotel',
          },
        ],
      },
      {
        date: '2025-07-23',
        day: 'Tuesday',
        segments: [
          {
            id: 'seg3',
            type: 'train',
            status: 'confirmed',
            title: 'Train to Stockholm',
            provider: 'SJ',
            confirmationCode: 'X2000-538',
            startTime: '12:12',
            endTime: '17:20',
            startLocation: 'Copenhagen Central Station',
            endLocation: 'Stockholm Central Station',
            startLocationShort: 'København H',
            endLocationShort: 'Stockholm C',
            duration: '5h 8m',
            details: { Platform: '7', Coach: '3', Seat: '24' },
          },
          {
            id: 'seg4',
            type: 'lodging',
            status: 'confirmed',
            title: 'Stockholm Airbnb',
            provider: 'Airbnb',
            confirmationCode: 'HMJ3P2QY1',
            startTime: '18:30',
            endTime: '10:00 (July 26)',
            startLocation: 'Gamla Stan, Stockholm',
            endLocation: 'Gamla Stan, Stockholm',
            startLocationShort: 'Gamla Stan',
            endLocationShort: 'Gamla Stan',
          },
        ],
      },
      {
        date: '2025-07-26',
        day: 'Friday',
        segments: [
          {
            id: 'seg5',
            type: 'ferry',
            status: 'delayed',
            title: 'Ferry to Helsinki',
            provider: 'Viking Line',
            confirmationCode: 'VL-887123',
            startTime: '16:30',
            endTime: '10:10 (July 27)',
            startLocation: 'Stadsgården, Stockholm',
            endLocation: 'Katajanokka, Helsinki',
            startLocationShort: 'Stockholm Port',
            endLocationShort: 'Helsinki Port',
            duration: '17h 40m',
            details: { 'New Departure': '17:00', Cabin: 'A4 - 10231', Deck: '10' },
          },
        ],
      },
    ],
  },
  {
    id: 'nyc-2025',
    title: 'Weekend in New York',
    startDate: '2025-08-15',
    endDate: '2025-08-18',
    image: {
      url: 'https://placehold.co/600x400.png',
      aiHint: 'new york',
    },
    itinerary: [
      {
        date: '2025-08-15',
        day: 'Friday',
        segments: [
          {
            id: 'seg6',
            type: 'flight',
            status: 'confirmed',
            title: 'Flight to JFK',
            provider: 'Delta',
            confirmationCode: 'DL421',
            startTime: '09:15',
            endTime: '12:05',
            startLocation: 'San Francisco International',
            endLocation: 'John F. Kennedy International',
            startLocationShort: 'SFO',
            endLocationShort: 'JFK',
            duration: '5h 50m',
          },
          {
            id: 'seg7',
            type: 'lodging',
            status: 'confirmed',
            title: 'The Hoxton, Williamsburg',
            provider: 'The Hoxton',
            confirmationCode: 'HX98765',
            startTime: '15:00',
            endTime: '12:00 (Aug 18)',
            startLocation: '97 Wythe Ave, Brooklyn, NY 11249',
            endLocation: '97 Wythe Ave, Brooklyn, NY 11249',
            startLocationShort: 'The Hoxton',
            endLocationShort: 'The Hoxton',
          },
        ],
      },
    ],
  },
];


export const inboxData: InboxMessage[] = [
  {
    id: 'msg1',
    summary: '✈️ Flight Delayed 30m',
    from: 'Viking Line',
    subject: 'Important: Your ferry to Helsinki is delayed',
    status: 'parsed',
    received: 'Today, 9:15 AM',
  },
  {
    id: 'msg2',
    summary: '🏨 Hotel Check-in Tomorrow',
    from: 'Booking.com',
    subject: 'Reminder: Your booking at Absalon Hotel',
    status: 'parsed',
    received: 'Yesterday, 8:00 PM',
  },
  {
    id: 'msg3',
    summary: '⚠️ Review Needed',
    from: 'GetYourGuide',
    subject: 'Confirmation: Viking Museum Tour',
    status: 'unmatched',
    received: 'July 18, 2:44 PM',
  },
  {
    id: 'msg4',
    summary: '⚠️ Booking Conflict',
    from: 'Flixbus',
    subject: 'Your bus ticket to Oslo',
    status: 'conflict',
    received: 'July 17, 11:10 AM',
  },
  {
    id: 'msg5',
    summary: '✅ Train Details Confirmed',
    from: 'SJ Rail',
    subject: 'Your e-ticket for Stockholm is ready',
    status: 'parsed',
    received: 'July 15, 6:21 PM',
  },
];

export const connectionsData: Connection[] = [
  {
    id: 'conn1',
    from: 'Copenhagen Airport (CPH)',
    to: 'Absalon Hotel',
    fromType: 'flight',
    toType: 'lodging',
    options: [
      {
        type: 'Public',
        duration: '15 min',
        cost: '$5',
        provider: 'DSB Train',
        description: 'Fastest public route via København H station.',
        isBest: 'Fastest',
      },
      {
        type: 'Rideshare',
        duration: '25 min',
        cost: '$30-40',
        provider: 'Uber/Viggo',
        description: 'Direct to door, subject to traffic.',
        isBest: null,
      },
      {
        type: 'Walk',
        duration: '1h 45m',
        cost: 'Free',
        provider: 'On Foot',
        description: 'Not recommended with luggage.',
        isBest: 'Eco',
      },
    ],
  },
  {
    id: 'conn2',
    from: 'Stockholm Central Station',
    to: 'Gamla Stan Airbnb',
    fromType: 'train',
    toType: 'lodging',
    options: [
      {
        type: 'Public',
        duration: '5 min',
        cost: '$4',
        provider: 'T-bana (Metro)',
        description: 'One stop to Gamla Stan station.',
        isBest: null,
      },
      {
        type: 'Walk',
        duration: '15 min',
        cost: 'Free',
        provider: 'On Foot',
        description: 'Pleasant walk through the city center.',
        isBest: 'Cheapest',
      },
      {
        type: 'Rideshare',
        duration: '10 min',
        cost: '$15-20',
        provider: 'Bolt/Uber',
        description: 'Quick but may be slower due to pedestrian areas.',
        isBest: null,
      },
    ],
  },
];